// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUcgd526Reb5o8qHd3SYGSLDVcVZizvmg',
    appId: '1:1094489315981:web:6f6500b7823d8dae18a0c4',
    messagingSenderId: '1094489315981',
    projectId: 'e-bus-pass-ac934',
    authDomain: 'e-bus-pass-ac934.firebaseapp.com',
    storageBucket: 'e-bus-pass-ac934.firebasestorage.app',
    measurementId: 'G-KJ8VYQG79H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQUXdzd2eKqtFkHobsHHxUedpewmkw50U',
    appId: '1:1094489315981:android:9cf58f3181ce1f4918a0c4',
    messagingSenderId: '1094489315981',
    projectId: 'e-bus-pass-ac934',
    storageBucket: 'e-bus-pass-ac934.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjMb5WgQA3dPAjLMEXumU34hh1Ypj5Fw0',
    appId: '1:1094489315981:ios:ca7743a9bb2a096118a0c4',
    messagingSenderId: '1094489315981',
    projectId: 'e-bus-pass-ac934',
    storageBucket: 'e-bus-pass-ac934.firebasestorage.app',
    iosBundleId: 'com.example.busPassApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjMb5WgQA3dPAjLMEXumU34hh1Ypj5Fw0',
    appId: '1:1094489315981:ios:ca7743a9bb2a096118a0c4',
    messagingSenderId: '1094489315981',
    projectId: 'e-bus-pass-ac934',
    storageBucket: 'e-bus-pass-ac934.firebasestorage.app',
    iosBundleId: 'com.example.busPassApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUcgd526Reb5o8qHd3SYGSLDVcVZizvmg',
    appId: '1:1094489315981:web:337f8572f15013ba18a0c4',
    messagingSenderId: '1094489315981',
    projectId: 'e-bus-pass-ac934',
    authDomain: 'e-bus-pass-ac934.firebaseapp.com',
    storageBucket: 'e-bus-pass-ac934.firebasestorage.app',
    measurementId: 'G-6P2VR2SPYH',
  );
}
